#!/bin/bash

dnf -y update
sudo dnf -y install php php-pear php-mysqlnd php-pdo php-bcmath php-zip php-openssl php-ctype php-json php-xml php-mbstring

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer

composer global require laravel/installer

echo composer install complete.
echo exec "composer create-project --prefer-dist laravel/laravel PROJECT-NAME", create a laravel project.
exit

